module.exports = [
  {
    currencies: ['RUB'],
    code: 'tinkoff',
    title: 'Tinkoff Bank',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'gazprombank',
    title: 'Газпромбанк',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'sber',
    title: 'Сбер',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'vtb',
    title: 'ВТБ',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'sovkombank',
    title: 'Совкомбанк',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'raiffaizen',
    title: 'РайффайзенБанк',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'alfabank',
    title: 'Альфа Банк',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'pochtabank',
    title: 'Почта Банк',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'bksbank',
    title: 'БКС Банк',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'mtsbank',
    title: 'МТС Банк',
    minAmount: 200,
    maxAmount: 150000,
  },
  {
    currencies: ['UAH'],
    code: 'privatbank',
    title: 'ПриватБанк',
    minAmount: 100,
    maxAmount: 50000,
  },
  {
    currencies: ['UAH'],
    code: 'monobank',
    title: 'monobank',
    minAmount: 100,
    maxAmount: 50000,
  },
  {
    currencies: ['IDR'],
    code: 'bni',
    title: 'BNI',
    minAmount: 100000,
    maxAmount: 150000000,
  },
  {
    currencies: ['IDR'],
    code: 'bca',
    title: 'BCA',
    minAmount: 100000,
    maxAmount: 150000000,
  },
  {
    currencies: ['IDR'],
    code: 'permata',
    title: 'Permata',
    minAmount: 100000,
    maxAmount: 150000000,
  },
  {
    currencies: ['CNY'],
    code: 'icbc',
    title: 'ICBC',
    minAmount: 50,
    maxAmount: 750000,
  },
  {
    currencies: ['CNY'],
    code: 'bankofchina',
    title: 'Bank of China',
    minAmount: 50,
    maxAmount: 750000,
  },
  {
    currencies: ['PLN'],
    code: 'bankpekao',
    title: 'Bank Pekao',
    minAmount: 30,
    maxAmount: 100000,
  },
  {
    currencies: ['THB'],
    code: 'krungsribank',
    title: 'Krungsri bank',
    minAmount: 100,
    maxAmount: 100000,
  },
  {
    currencies: ['CAD'],
    code: 'rotalbankofcanada',
    title: 'Royal Bank of Canada',
    minAmount: 10,
    maxAmount: 10000,
  },
  {
      currencies: ['TRY'],
      code: 'trybank',
      title: 'Bank transfer',
      minAmount: 100,
      maxAmount: 450000,
  },
  {
    currencies: ['USD'],
    code: 'usdbank',
    title: 'Bank transfer',
    minAmount: 10,
    maxAmount: 100000,
  },
  {
    currencies: ['EUR'],
    code: 'eurbank',
    title: 'Bank transfer',
    minAmount: 10,
    maxAmount: 100000,
  },
  {
    currencies: ['GBP'],
    code: 'gbpbank',
    title: 'Bank transfer',
    minAmount: 10,
    maxAmount: 100000,
  },
];