module.exports = [
  {
    currencies: ['RUB'],
    code: 'tinkoff',
    title: 'Tinkoff Bank',
    minAmount: 5000,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'gazprombank',
    title: 'Газпромбанк',
    minAmount: 5000,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'sber',
    title: 'Сбер',
    minAmount: 5000,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'vtb',
    title: 'ВТБ',
    minAmount: 5000,
    maxAmount: 150000,
  },
  {
    currencies: ['RUB'],
    code: 'sovkombank',
    title: 'Совкомбанк',
    minAmount: 5000,
    maxAmount: 150000,
  },
  {
    currencies: ['UAH'],
    code: 'privatbank',
    title: 'ПриватБанк',
    minAmount: 1000,
    maxAmount: 50000,
  },
  {
    currencies: ['UAH'],
    code: 'monobank',
    title: 'monobank',
    minAmount: 1000,
    maxAmount: 50000,
  },
  {
    currencies: ['IDR'],
    code: 'bni',
    title: 'BNI',
    minAmount: 500000,
    maxAmount: 150000000,
  },
  {
    currencies: ['IDR'],
    code: 'bca',
    title: 'BCA',
    minAmount: 500000,
    maxAmount: 150000000,
  },
  {
    currencies: ['IDR'],
    code: 'permata',
    title: 'Permata',
    minAmount: 500000,
    maxAmount: 150000000,
  },
  {
    currencies: ['CNY'],
    code: 'icbc',
    title: 'ICBC',
    minAmount: 500,
    maxAmount: 10000,
  },
  {
    currencies: ['CNY'],
    code: 'bankofchina',
    title: 'Bank of China',
    minAmount: 500,
    maxAmount: 10000,
  },
  {
    currencies: ['PLN'],
    code: 'bankpekao',
    title: 'Bank Pekao',
    minAmount: 500,
    maxAmount: 100000,
  },
  {
    currencies: ['THB'],
    code: 'krungsribank',
    title: 'Krungsri bank',
    minAmount: 500,
    maxAmount: 100000,
  },
  {
    currencies: ['CAD'],
    code: 'rotalbankofcanada',
    title: 'Royal Bank of Canada',
    minAmount: 500,
    maxAmount: 10000,
  },
];